export const fieldConfig = [
  { name: 'firstName', label: 'First Name', type: 'text', required: true, minLength: 2 },
  { name: 'lastName', label: 'Last Name', type: 'text', required: true, minLength: 2 },
  { name: 'email', label: 'Email', type: 'email', required: true, pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/ },
  { name: 'phone', label: 'Phone', type: 'tel', required: true, pattern: /^\+?\d{10,15}$/ },
  { name: 'age', label: 'Age', type: 'number', required: true, min: 18, max: 120 },
  { name: 'address', label: 'Address', type: 'text', required: true, minLength: 5 },
  { name: 'city', label: 'City', type: 'text', required: true },
  { name: 'country', label: 'Country', type: 'text', required: true },
  { name: 'zipCode', label: 'Zip Code', type: 'text', required: true, pattern: /^\d{5}(-\d{4})?$/ },
  { name: 'occupation', label: 'Occupation', type: 'text', required: false },
  { name: 'company', label: 'Company', type: 'text', required: false },
  { name: 'website', label: 'Website', type: 'url', required: false, pattern: /^https?:\/\/.+/ },
  { name: 'birthDate', label: 'Birth Date', type: 'date', required: true },
  { name: 'gender', label: 'Gender', type: 'select', required: true, options: ['Male', 'Female', 'Other'] },
  { name: 'nationality', label: 'Nationality', type: 'text', required: true },
  { name: 'emergencyContact', label: 'Emergency Contact', type: 'tel', required: true, pattern: /^\+?\d{10,15}$/ },
  { name: 'hobbies', label: 'Hobbies', type: 'text', required: false },
  { name: 'education', label: 'Education', type: 'text', required: true },
  { name: 'language', label: 'Language', type: 'text', required: true },
  { name: 'comments', label: 'Comments', type: 'textarea', required: false, maxLength: 500 },
]; 